### ISSUE TITLE
Free entries in selection field for Lifecycle Stage

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#18]
**Object path:** GeneralInformation > ModelMetaData >  LifecycleStage
**Description:** It should be possible to set the attribute both with default entries from a dropdown box and with a free entry if the default entries are not applicable
**Rationale:** You save the attribute GeneralInformation > ModelMetaData > IndividualLifecycleStage and inconsistent entries for the Lifecycle Stage are prevented.

**Comment by DrCaFr** [comment]
I cannot find any attribute "**Individual**LifecycleStage" in the current XSD versions.
