### ISSUE TITLE
Attribute IndividualLifecycleStage can be omitted conditionally

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#21]
**Object path:** GeneralInformation > ModelMetaData >  IndividualLifecycleStage
**Description:** Can be omitted if #18 is implemented
**Rationale:** Man spart sich ein Attribut und inkonsistente Angaben werden unterbunden

**Comment by DrCaFr** [comment]
See my comment https://github.com/PMSFIT/SSPTraceability/issues/18#issuecomment-578846291 to https://github.com/PMSFIT/SSPTraceability/issues/18.
