### ISSUE TITLE
Attribute IndividualConfidentialLevel can be omitted conditionally

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#23]
**Object path:** GeneralInformation > ModelMetaData >  IndividualConfidentialityLevel
**Description:** Can be omitted if #22 is converted
**Rationale:** You save one attribute and inconsistent entries are prevented

**Comment by DrCaFr** [comment]
I cannot find attribute "IndividualConfidentialLevel" in current XSD versions
