### ISSUE TITLE
Anonymous mailboxes instead of concrete persons

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#24]
**Object path:** GeneralInformation > PersonAndOrganisation
**Description:** Could anonymous mailboxes also be described here?
**Rationale:** Sharing of personal information is not always desirable and individuals may also change their responsibilities

**Comment by DrCaFr** [comment]
From my perception, this is implied by the 2nd half of the name "PersonAnd**Organisation**".
