### ISSUE TITLE
Rename Object PropertyRights

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#25]
**Object path:** GeneralInformation > IntellectualPropertyRights
**Description:** The object should be renamed to make it easier to understand, e.g. to "IsOpen" or "Restricted
**Rationale:** The naming is better based on the value entries and thus makes the attribute more comprehensible

**Comment by DrCaFr** [comment]
I cannot find attribute "IntellectualPropertyRights" in current XSD versions.
