### ISSUE TITLE
Adjust attribute description for solver name

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#32]
**Object path:** ModelExecutionInformation > SolverSettings > SolverName
**Description:** In the description of the attribute recommended instead of required write

**Comment by DrCaFr** [comment]
Currently, I cannot see _any_ description:
~~~
<xs:appinfo xml:lang="en">
	<displayName>Solver Name</displayName>
	<description></description>
</xs:appinfo>
~~~
