### ISSUE TITLE
Signals as initial values

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#38]
**Object path:** ModelContentAndUsageInformation >  PortsAndParameters > InitialValue
**Description:** Es kann auch variable initiale Verte geben, die sich z.B. aus Signalen ergeben

**Comment by DrCaFr** [comment]
From my point of view, an _initial_ value is a value at a single point in time, namely the simulation's start. 
Hence, it is a _constant_.

Varying parameters / signals are of course possible. But then, I'd call them "boundary conditions".
