### ISSUE TITLE
Several PhysicalDomains possible

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#39]
**Object path:** ModelContentAndUsageInformation >  PhysicalDomain > PhysicalDomain
**Description:** An FMU can also be assigned to several domains, but this is not shown in the scheme. The schema should have a list object here, but this is currently not the case.

**Comment by DrCaFr** [comment]
Is it meaningful to use an element name _twice_: 
~~~
<xs:element name="PhysicalDomain">
	<xs:annotation>
		<xs:documentation xml:lang="en">
			Specification of the captured physical domains of the model.
		</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="PhysicalDomain" type="xs:string">
				<xs:annotation>
					<xs:documentation xml:lang="en">
						List of physical domains (multiple selection allowed).
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
~~~
I'd suggest using "PhysicalDomain**s**" for the latter, list-type one.
