### ISSUE TITLE
AnalysisPhase, RequirementsPhase zu ergänzen

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#4]
AnalysisPhase, RequirementsPhase Zu ergänzen
• Die beiden Phasen müssen entsprechende Äquivalente (Prozessschritte) im übergeordneten Prozess haben -> Verbindung zu Page 60: 6.2.1 Generic simulation based decision process
• Master ist übergeordneter Prozess
   o Informationen werden in untergeordnete Prozessschritte Kopiert
   o Dort aber keine Modifikationen
   o Falls Änderungen notwendig werden -> Change Request an übergeordneten Prozess
   o Kopierte Informationen (Kapitel) notwendig wegen Traceability Information Chain
• Übergeordnete Prozessschritte, deren Datenstruktur kann von dieser Struktur abweichen
   o Mapping muss möglich sein
   o Übergeordnete Prozesse müssen entsprechend angepasst werden

**Comment by tabbertpeter** [comment]
AnalysisPhase, RequirementsPhase Zu ergänzen
• Die beiden Phasen müssen entsprechende Äquivalente (Prozessschritte) im übergeordneten Prozess haben -> Verbindung zu Page 60: 6.2.1 Generic simulation based decision process
• Master ist übergeordneter Prozess
   o Informationen werden in untergeordnete Prozessschritte Kopiert
   o Dort aber keine Modifikationen
   o Falls Änderungen notwendig werden -> Change Request an übergeordneten Prozess
   o Kopierte Informationen (Kapitel) notwendig wegen Traceability Information Chain
• Übergeordnete Prozessschritte, deren Datenstruktur kann von dieser Struktur abweichen
   o Mapping muss möglich sein
   o Übergeordnete Prozesse müssen entsprechend angepasst werden

**Comment by DrCaFr** [comment]
__Decision:__
As a disclaimer, preconditions for application of simulation traceability need to be described precisely. 
Process description needs to be done some where else - it is not within our scope. 

__To-Do:__ 
Create disclaimer.

**Comment by tabbertpeter** [comment]
Disclaimer is available on page 5

**Comment by tabbertpeter** [comment]
Scheint nicht mehr aktuell zu  bzw. das Problem vermutlich längst eliminiert
