### ISSUE TITLE
Inconsistency of Specification and Repository

### ISSUE THREAD

**Issue by mdeppe** [PMSFIT/SSPTraceability#41]
When looking at the repo and the specification there is a high inconsistency in regards to the XML schemas.
It is really unclear what it is all about and I'm getting confused:
- Specification is about STMD and SRMD
- Example is using SMMD
- Repository contains schemas for SPMD, SMMD, STMD, SRMD

So what is the role of SMMD and SPMD?

**Comment by ClemensLinnhoff** [comment]
I just stumbled across the same problems. Why was this issue closed?
There are still SMMD files in the example. The schema file referenced in those files is "../../../SMMD.xsd", which does not exist. And I have the same question: What is the difference between SRMD and SMMD?

This is linked to #51 which was also prematurely closed. I am still unable to validate the schema of an SRMD file.
