### ISSUE TITLE
Document CDP

### ISSUE THREAD

**Issue by pmai** [PMSFIT/SSPTraceability#49]

**Comment by pmai** [comment]
Documentation to take place in main documentation branches once the CDP branch (feature/sbet-draft) has been merged, see #44.

**Comment by tabbertpeter** [comment]
1. determine location of documentation within the SSP Traceability.
2. align test with CSP documentation
3. implement documentation

**Comment by Hans-Martin-Heinkel** [comment]
clarify if last phase of CDP decision or Decide Fulfillment
6.1.3 text is missing -> extract part of CDP Process
6.1.6 use text from CDP

**Comment by Hans-Martin-Heinkel** [comment]
clarify if last phase of CDP decision or Decide Fulfillment in picture
clarify if at begin of chapter 6 picture of CDP
