### ISSUE TITLE
Page 24 Bild 5 Block GUID  Ist Block GUID TOP Level? Falls ja wie Vorgaben zum befüllen mit Daten? •	Immer das Tool, Autor des aktuell erstellenden Tools des Kapitels? •	Kopie der entsprechenden Kapitelinformationen o	Ist zwar Redundanz, macht aber globale Auswertung von GlueParticeln einfacher Da es viele Arten von GlueParticeln geben wird •	Wie sieht Kurzbeschreibung über Art des GlueParticel aus •	stehen diese Informationen hier GUID

### ISSUE THREAD

**Issue by tabbertpeter** [PMSFIT/SSPTraceability#5]
Page 24 Bild 5 Block GUID 
Ist Block GUID TOP Level? Falls ja wie Vorgaben zum befüllen mit Daten?
•	Immer das Tool, Autor des aktuell erstellenden Tools des Kapitels?
•	Kopie der entsprechenden Kapitelinformationen
o	Ist zwar Redundanz, macht aber globale Auswertung von GlueParticeln einfacher

Da es viele Arten von GlueParticeln geben wird
•	Wie sieht Kurzbeschreibung über Art des GlueParticel aus
•	stehen diese Informationen hier GUID

**Comment by DrCaFr** [comment]
__Description:__  
Current semantics of "ssc:ATopLevelMetaData.generationTool" is: Tool, which wrote the actual file.  
This is _not_ the tool, which initially created the first glue particle of a derivation chain, the actual file may belong to. 

__Decision:__  
Issue retracted by requester.
